NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.uppclorg1.uppcl.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.uppclorg1.uppcl.com-cert.pem
    OrganizationalUnitIdentifier: peer
