# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.4'

volumes:
  peer0.paytm.uppcl.com:
  peer1.paytm.uppcl.com:
  
networks:
  bymn:
    external:
      name: $SWARM_NETWORK
    


services:
  ca2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.paytm.uppcl.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.paytm.uppcl.com-cert.pem
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.paytm.uppcl.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e64dcb4e51c051f14bc35b947ffd051390173484f452d44925df45a2cb9bdfc9_sk
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e64dcb4e51c051f14bc35b947ffd051390173484f452d44925df45a2cb9bdfc9_sk
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.paytm.uppcl.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/e64dcb4e51c051f14bc35b947ffd051390173484f452d44925df45a2cb9bdfc9_sk  -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/paytm.uppcl.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca2
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $ORG2_HOSTNAME

    ports:
     - published: 7054
       target: 7054
       mode: host
    networks:
      bymn:
        aliases:
          - ca.paytm.uppcl.com

  org2couchdb0:
    container_name: org2couchdb0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER= couchdb
      - COUCHDB_PASSWORD=couchdb123  
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $ORG2_HOSTNAME
    ports:
     - published: 5984 
       target: 5984
       mode: host
    networks:
      bymn:
        aliases:
          - couchdb0.paytm.uppcl.com
  org2couchdb1:
    container_name: org2couchdb1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER= couchdb
      - COUCHDB_PASSWORD=couchdb123  
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $ORG2_HOSTNAME
    ports:
     - published: 5986 
       target: 5984
       mode: host
    networks:
      bymn:
        aliases:
          - couchdb1.paytm.uppcl.com
  org2peer0:
    container_name: org2peer0
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.paytm.uppcl.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchdb123

      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.paytm.uppcl.com
      - CORE_PEER_ADDRESS=peer0.paytm.uppcl.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.paytm.uppcl.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.paytm.uppcl.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/paytm.uppcl.com/peers/peer0.paytm.uppcl.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/paytm.uppcl.com/peers/peer0.paytm.uppcl.com/tls:/etc/hyperledger/fabric/tls
        #- ./crypto-config/peerOrganizations/paytm.uppcl.com/peers/peer0.paytm.uppcl.com/ca:/etc/hyperledger/fabric/ca
        - peer0.paytm.uppcl.com:/var/hyperledger/production
    
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $ORG2_HOSTNAME

    ports:
            - published: 7051
              target: 7051
              mode: host
            - published: 7053
              target: 7053
              mode: host
    networks:
      bymn:
        aliases:
          - peer0.paytm.uppcl.com

  org2peer1:
    container_name: org2peer1
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.paytm.uppcl.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchdb123
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.paytm.uppcl.com
      - CORE_PEER_ADDRESS=peer1.paytm.uppcl.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.paytm.uppcl.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.paytm.uppcl.com:8051
      - CORE_PEER_LOCALMSPID=Org2MSP

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/paytm.uppcl.com/peers/peer1.paytm.uppcl.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/paytm.uppcl.com/peers/peer1.paytm.uppcl.com/tls:/etc/hyperledger/fabric/tls
        #- ./crypto-config/peerOrganizations/paytm.uppcl.com/peers/peer1.paytm.uppcl.com/ca:/etc/hyperledger/fabric/ca
        - peer1.paytm.uppcl.com:/var/hyperledger/production
    
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $ORG2_HOSTNAME

    ports:
            - published: 8051
              target: 7051
              mode: host
            - published: 8053
              target: 7053
              mode: host
    networks:
      bymn:
        aliases:
          - peer1.paytm.uppcl.com

  org2cli:
    container_name: org2cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $ORG2_HOSTNAME

    environment:

      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.paytm.uppcl.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/paytm.uppcl.com/peers/peer0.paytm.uppcl.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/paytm.uppcl.com/peers/peer0.paytm.uppcl.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/paytm.uppcl.com/peers/peer0.paytm.uppcl.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/paytm.uppcl.com/users/Admin@paytm.uppcl.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode/:/opt/gopath/src/github.com/chaincode
        - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - bymn
